[package]
name = "cheat_sheet_genshin"
version = "0.6.3"
edition = "2021"
authors = ["Xanthus58, Zinziez"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"